apiVersion: v1
data:
  poseidon_config.yaml: |
    schedulerName: poseidon
    firmamentAddress: 10.43.88.49
    kubeConfig: "/home/.kube/config_fromjson"
    kubeVersion: 1.8
    statsServerAddress: 0.0.0.0:9091
    schedulingInterval: 10
    firmamentPort: 9090
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"poseidon_config.yaml":"schedulerName: poseidon\nfirmamentAddress: 0.0.0.0\nkubeConfig: \"/home/.kube/config_fromjson\"\nkubeVersion: 1.8\nstatsServerAddress: 0.0.0.0:9091\nschedulingInterval: 10\nfirmamentPort: 9090\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"poseidon-config","namespace":"kube-system"}}
  creationTimestamp: "2024-08-09T11:41:48Z"
  name: poseidon-config
  namespace: kube-system
  resourceVersion: "12192"
  uid: 276744cd-6d79-455d-9cda-e99bb9dc0577
