apiVersion: appgroup.diktyo.x-k8s.io/v1alpha1
kind: AppGroup
metadata:
  name: sock-shop
spec:
  numMembers: 13
  topologySortingAlgorithm: AlternateKahn
  workloads:
    - workload:
        kind: Deployment
        name: front-end-v1
        selector: front-end
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies:
        - workload:
            kind: Deployment
            name: catalogue
            selector: catalogue
            apiVersion: apps/v1
            namespace: sock-shop
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            name: orders
            selector: orders
            apiVersion: apps/v1
            namespace: sock-shop
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            name: payment
            selector: payment
            apiVersion: apps/v1
            namespace: sock-shop
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        name: orders
        selector: orders
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies:
        - workload:
            kind: Deployment
            name: orders-db
            selector: orders-db
            apiVersion: apps/v1
            namespace: sock-shop
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        name: payment
        selector: payment
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies:
        - workload:
            kind: Deployment
            name: user-db
            selector: user-db
            apiVersion: apps/v1
            namespace: sock-shop
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        name: catalogue
        selector: catalogue
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies:
        - workload:
            kind: Deployment
            name: catalogue-db
            selector: catalogue-db
            apiVersion: apps/v1
            namespace: sock-shop
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        name: user
        selector: user
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies:
        - workload:
            kind: Deployment
            name: user-db
            selector: user-db
            apiVersion: apps/v1
            namespace: sock-shop
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        name: shipping
        selector: shipping
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies:
        - workload:
            kind: Deployment
            name: queue-master
            selector: queue-master
            apiVersion: apps/v1
            namespace: sock-shop
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        name: queue-master
        selector: queue-master
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies:
        - workload:
            kind: Deployment
            name: rabbitmq
            selector: rabbitmq
            apiVersion: apps/v1
            namespace: sock-shop
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        name: rabbitmq
        selector: rabbitmq
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies: []
    - workload:
        kind: Deployment
        name: carts-db
        selector: carts-db
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies: []
    - workload:
        kind: Deployment
        name: catalogue-db
        selector: catalogue-db
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies: []
    - workload:
        kind: Deployment
        name: user-db
        selector: user-db
        apiVersion: apps/v1
        namespace: sock-shop
      dependencies: []
